In [1]:
# Importing Pandas library
import pandas as pd

In [2]:
# Reading the CSV into a DataFrame, then previewing the DataFrame
df = pd.read_csv('Employee Turnover Dataset.csv')
df

,EmployeeNumber,Age,Tenure,Turnover,HourlyRate,HoursWeekly,CompensationType,AnnualSalary,DrivingCommuterDistance,JobRoleArea,Gender,MaritalStatus,NumCompaniesPreviouslyWorked,AnnualProfessionalDevHrs,PaycheckMethod,TextMessageOptIn
0,1,28,6,Yes,$24.37,40,Salary,50689.6,89,Research,Female,Married,3.0,7.0,Mail Check,Yes
1,2,33,2,Yes,$24.37,40,Salary,50689.6,89,Research,Female,Married,6.0,7.0,Mail Check,Yes
2,3,22,1,No,$22.52,40,Salary,46841.6,35,Information_Technology,Female,Single,1.0,8.0,Mailed Check,Yes
3,4,23,1,No,$22.52,40,Salary,46841.6,35,Information_Technology,Female,Single,3.0,NaN,Mailed Check,Yes
4,5,40,6,No,$88.77,40,Salary,284641.6,12,Sales,Prefer Not to Answer,Single,7.0,NaN,Mail Check,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10194,95,48,13,Yes,$85.40,40,Salary,177632.0,31,Research,Male,Single,7.0,5.0,Mail Check,NaN
10195,96,54,17,No,$85.40,40,Salary,177632.0,31,Research,Male,Single,2.0,25.0,Mail Check,Yes
10196,97,44,6,No,$71.90,40,Salary,149552.0,32,Marketing,Male,Married,6.0,NaN,Mail Check,Yes
10197,98,58,19,No,$71.90,40,Salary,149552.0,32,Marketing,Male,Married,5.0,23.0,Mail Check,Yes
10198,99,48,17,Yes,$71.33,40,Salary,148075.2,50,Sales,Prefer Not to Answer,Married,8.0,8.0,Mail Check,Yes

In [3]:
# Displaying the duplicated rows of the DataFrame
df[df.duplicated()]

,EmployeeNumber,Age,Tenure,Turnover,HourlyRate,HoursWeekly,CompensationType,AnnualSalary,DrivingCommuterDistance,JobRoleArea,Gender,MaritalStatus,NumCompaniesPreviouslyWorked,AnnualProfessionalDevHrs,PaycheckMethod,TextMessageOptIn
10100,1,28,6,Yes,$24.37,40,Salary,50689.6,89,Research,Female,Married,3.0,7.0,Mail Check,Yes
10101,2,33,2,Yes,$24.37,40,Salary,50689.6,89,Research,Female,Married,6.0,7.0,Mail Check,Yes
10102,3,22,1,No,$22.52,40,Salary,46841.6,35,Information_Technology,Female,Single,1.0,8.0,Mailed Check,Yes
10103,4,23,1,No,$22.52,40,Salary,46841.6,35,Information_Technology,Female,Single,3.0,NaN,Mailed Check,Yes
10104,5,40,6,No,$88.77,40,Salary,284641.6,12,Sales,Prefer Not to Answer,Single,7.0,NaN,Mail Check,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10194,95,48,13,Yes,$85.40,40,Salary,177632.0,31,Research,Male,Single,7.0,5.0,Mail Check,NaN
10195,96,54,17,No,$85.40,40,Salary,177632.0,31,Research,Male,Single,2.0,25.0,Mail Check,Yes
10196,97,44,6,No,$71.90,40,Salary,149552.0,32,Marketing,Male,Married,6.0,NaN,Mail Check,Yes
10197,98,58,19,No,$71.90,40,Salary,149552.0,32,Marketing,Male,Married,5.0,23.0,Mail Check,Yes
10198,99,48,17,Yes,$71.33,40,Salary,148075.2,50,Sales,Prefer Not to Answer,Married,8.0,8.0,Mail Check,Yes

In [4]:
# New cleaned_df DataFrame with all 99 duplicated rows dropped
cleaned_df = df.drop_duplicates()

# Checking to make sure all duplicates were dropped
print(f"Duplicate values: {cleaned_df.duplicated().sum()}")

Duplicate values: 0

In [5]:
# Comparing the original DataFrame to the cleaned DataFrame with duplicate rows removed
print(df.shape)
print(cleaned_df.shape)

(10199, 16)
(10100, 16)

In [6]:
# Counting the amount of missing values in the DataFrame for each column
cleaned_df.isna().sum()

EmployeeNumber                     0
Age                                0
Tenure                             0
Turnover                           0
HourlyRate                         0
HoursWeekly                        0
CompensationType                   0
AnnualSalary                       0
DrivingCommuterDistance            0
JobRoleArea                        0
Gender                             0
MaritalStatus                      0
NumCompaniesPreviouslyWorked     663
AnnualProfessionalDevHrs        1947
PaycheckMethod                     0
TextMessageOptIn                2258
dtype: int64

In [7]:
# Distribution of NumCompaniesPreviouslyWorked column
cleaned_df['NumCompaniesPreviouslyWorked'].value_counts(dropna = False)

NumCompaniesPreviouslyWorked
1.0    1497
2.0    1469
3.0    1447
6.0    1047
4.0    1017
5.0     983
7.0     679
NaN     663
8.0     652
9.0     646
Name: count, dtype: int64

In [8]:
# Distribution of unique values
cleaned_df['Age'].value_counts().sort_index(ascending = False)

Age
61    293
60    296
59    290
58    296
57    279
56    303
55    243
54    293
53    289
52    266
51    278
50    265
49    278
48    311
47    295
46    305
45    281
44    315
43    317
42    300
41    299
40    375
39    444
38    382
37    422
36    403
35    186
34    201
33    189
32    213
31    184
30    202
29     88
28     78
27     89
26     91
25     89
24     96
23     82
22    102
21     92
Name: count, dtype: int64

In [9]:
# Median imputation for the NumCompaniesPrevioulyWorked column
# Finding the median value of the number of companies previously worked by age
median_by_age = cleaned_df.groupby('Age')['NumCompaniesPreviouslyWorked'].transform('median')

# Using loc to fill missing values in the column with the corresponding median_by_age value
cleaned_df.loc[:, 'NumCompaniesPreviouslyWorked'] = cleaned_df['NumCompaniesPreviouslyWorked'].fillna(median_by_age)

In [10]:
# Checking the distribution of NumCompaniesPreviouslyWorked again
cleaned_df['NumCompaniesPreviouslyWorked'].value_counts(dropna = False)

NumCompaniesPreviouslyWorked
5.0    1586
1.0    1497
2.0    1469
3.0    1447
4.0    1077
6.0    1047
7.0     679
8.0     652
9.0     646
Name: count, dtype: int64

In [11]:
# TextMessageOptIn distribution
cleaned_df['TextMessageOptIn'].value_counts(dropna = False)

TextMessageOptIn
Yes    7299
NaN    2258
No      543
Name: count, dtype: int64

In [12]:
# Mode imputation for TextMessageOptIn column
# Finding the mode of the column; [0] returns the first and only element of the Series from using mode - Yes
mode_value = cleaned_df['TextMessageOptIn'].mode()[0]

# Then use loc to fill missing values in the column with the mode
cleaned_df.loc[:, 'TextMessageOptIn'] = cleaned_df['TextMessageOptIn'].fillna(mode_value)

In [13]:
# Checking the distribution of TextMessageOptIn distribution
cleaned_df['TextMessageOptIn'].value_counts(dropna = False)

TextMessageOptIn
Yes    9557
No      543
Name: count, dtype: int64

In [14]:
# Distribution of AnnualProfessionalDevHrs
cleaned_df['AnnualProfessionalDevHrs'].value_counts(dropna = False)

AnnualProfessionalDevHrs
NaN     1947
23.0     429
10.0     419
14.0     411
13.0     409
25.0     407
6.0      403
11.0     395
5.0      395
7.0      390
9.0      389
12.0     385
22.0     385
18.0     383
15.0     382
19.0     379
17.0     376
8.0      372
24.0     370
16.0     359
20.0     359
21.0     356
Name: count, dtype: int64

In [15]:
# Distribution of unique values
cleaned_df['JobRoleArea'].value_counts()

JobRoleArea
Research                  2005
Sales                     1988
Marketing                 1093
Manufacturing             1031
Laboratory                1007
Healthcare                1002
Human Resources            909
Information Technology     857
InformationTechnology       80
HumanResources              51
Information_Technology      42
Human_Resources             35
Name: count, dtype: int64

In [16]:
# Need to standardize some of the categorical values
# Create a mapping dictionary
role_mapping = {
    'Information Technology': 'InformationTechnology', 
    'Information_Technology': 'InformationTechnology',
    'Human_Resources': 'HumanResources',
    'Human Resources': 'HumanResources'}
# replace() method
cleaned_df.loc[:, 'JobRoleArea'] = cleaned_df['JobRoleArea'].replace(role_mapping)
# Distribution of unique values to check if it worked
cleaned_df['JobRoleArea'].value_counts()

JobRoleArea
Research                 2005
Sales                    1988
Marketing                1093
Manufacturing            1031
Laboratory               1007
Healthcare               1002
HumanResources            995
InformationTechnology     979
Name: count, dtype: int64

In [17]:
# Median imputation for the AnnualProfessionalDevHrs column
# Calculate the median values of annual professional dev hrs by job role
job_role_medians = cleaned_df.groupby('JobRoleArea')['AnnualProfessionalDevHrs'].transform('median')
    
# Using loc to fill missing values in the column with the corresponding job_role_medians value
cleaned_df.loc[:, 'AnnualProfessionalDevHrs'] = cleaned_df['AnnualProfessionalDevHrs'].fillna(job_role_medians)

In [18]:
# Checking the distribution of AnnualProfessionalDevHrs again
cleaned_df['AnnualProfessionalDevHrs'].value_counts(dropna = False)

AnnualProfessionalDevHrs
15.0    1962
14.0     607
23.0     429
10.0     419
13.0     409
25.0     407
6.0      403
5.0      395
11.0     395
7.0      390
9.0      389
12.0     385
22.0     385
18.0     383
19.0     379
17.0     376
8.0      372
24.0     370
16.0     359
20.0     359
21.0     356
14.5     171
Name: count, dtype: int64

Duplicated rows have been removed and missing values have been dealt with.
Time to check each column for other issues!

In [19]:
# Checking the EmployeeNumbers column
# Distribution of unique values to ensure each employee number only has one employee
cleaned_df['EmployeeNumber'].value_counts()

EmployeeNumber
1        1
6738     1
6731     1
6732     1
6733     1
        ..
3367     1
3368     1
3369     1
3370     1
10100    1
Name: count, Length: 10100, dtype: int64

Every employee has a unique number.

In [20]:
# Checking the Age column
# Descriptive statistics
cleaned_df['Age'].describe()

count    10100.000000
mean        44.078911
std         10.213311
min         21.000000
25%         37.000000
50%         44.000000
75%         53.000000
max         61.000000
Name: Age, dtype: float64

In [21]:
# Distribution of unique values
cleaned_df['Age'].value_counts().sort_index(ascending = False)

Age
61    293
60    296
59    290
58    296
57    279
56    303
55    243
54    293
53    289
52    266
51    278
50    265
49    278
48    311
47    295
46    305
45    281
44    315
43    317
42    300
41    299
40    375
39    444
38    382
37    422
36    403
35    186
34    201
33    189
32    213
31    184
30    202
29     88
28     78
27     89
26     91
25     89
24     96
23     82
22    102
21     92
Name: count, dtype: int64

Age column looks good. Everyone is 21 to 61 years old, which are normal ages at a company.

In [22]:
# Checking the Tenure column
# Descriptive Statistics
cleaned_df['Tenure'].describe()

count    10100.000000
mean         9.007624
std          5.512046
min          1.000000
25%          5.000000
50%          8.000000
75%         13.000000
max         20.000000
Name: Tenure, dtype: float64

In [23]:
# Distribution of unique values
cleaned_df['Tenure'].value_counts().sort_index(ascending = False)

Tenure
20    356
19    349
18    334
17    323
16    341
15    360
14    375
13    348
12    327
11    329
10    737
9     679
8     703
7     728
6     719
5     733
4     447
3     609
2     452
1     851
Name: count, dtype: int64

Tenure column looks good. No unreasonably high outliers nor negative numbers.

In [24]:
# Checking the Turnover column
# Summary of the data
cleaned_df['Turnover'].describe()

count     10100
unique        2
top          No
freq       5456
Name: Turnover, dtype: object

In [25]:
# Distribution of unique values
cleaned_df['Turnover'].value_counts().sort_index(ascending = False)

Turnover
Yes    4644
No     5456
Name: count, dtype: int64

Turnover column looks good. The values are consistent (Yes or No) and the distribution is reasonable.

In [26]:
# Checking the CompensationType column
# Summary of the data
cleaned_df['CompensationType'].describe()

count      10100
unique         1
top       Salary
freq       10100
Name: CompensationType, dtype: object

In [27]:
# Distribution of unique values
cleaned_df['CompensationType'].value_counts().sort_index(ascending = False)

CompensationType
Salary    10100
Name: count, dtype: int64

CompensationType column looks good. No values besides Salary so it's consistent.

In [28]:
# There was an error when trying to use describe() method with HourlyRate, even though I spelt the column name correctly
# Checking the names of the columns
cleaned_df.columns

Index(['EmployeeNumber', 'Age', 'Tenure', 'Turnover', 'HourlyRate ',
       'HoursWeekly', 'CompensationType', 'AnnualSalary',
       'DrivingCommuterDistance', 'JobRoleArea', 'Gender', 'MaritalStatus',
       'NumCompaniesPreviouslyWorked', 'AnnualProfessionalDevHrs',
       'PaycheckMethod', 'TextMessageOptIn'],
      dtype='object')

In [29]:
# HourlyRate has a a trailing space, need to rename the column
cleaned_df = cleaned_df.rename(columns = {'HourlyRate ': 'HourlyRate'})
# Checking the column names again
cleaned_df.columns

Index(['EmployeeNumber', 'Age', 'Tenure', 'Turnover', 'HourlyRate',
       'HoursWeekly', 'CompensationType', 'AnnualSalary',
       'DrivingCommuterDistance', 'JobRoleArea', 'Gender', 'MaritalStatus',
       'NumCompaniesPreviouslyWorked', 'AnnualProfessionalDevHrs',
       'PaycheckMethod', 'TextMessageOptIn'],
      dtype='object')

In [30]:
# Checking the HourlyRate column
# Summary of the data
cleaned_df['HourlyRate'].describe()

count       10100
unique       5244
top       $34.28
freq           11
Name: HourlyRate, dtype: object

In [31]:
# HourlyRate is an object that needs to be changed to a float64 because it's a numerical continuous
# Need to remove the $ before converting. 
cleaned_df['HourlyRate'] = cleaned_df['HourlyRate'].str.replace('$', '', regex = False).astype(float)
# Checking conversion
cleaned_df['HourlyRate'].dtype

dtype('float64')

In [32]:
# Descriptive statistics
cleaned_df['HourlyRate'].describe()

count    10100.000000
mean        52.838207
std         23.891318
min         17.210000
25%         31.080000
50%         48.930000
75%         73.902500
max         98.070000
Name: HourlyRate, dtype: float64

In [33]:
# Distribution of unique values
cleaned_df['HourlyRate'].value_counts().sort_index(ascending = False)

HourlyRate
98.07    1
98.06    1
98.05    1
98.04    2
98.01    1
        ..
17.37    1
17.36    1
17.34    4
17.22    1
17.21    1
Name: count, Length: 5244, dtype: int64

HourlyRate column looks good. No unusual rates. Highest rate is reasonable for a senior employee or management position; lowest is normal for an entry-level position.

In [34]:
# Checking the HoursWeekly column
# Descriptive statistics
cleaned_df['HoursWeekly'].describe()

count    10100.0
mean        40.0
std          0.0
min         40.0
25%         40.0
50%         40.0
75%         40.0
max         40.0
Name: HoursWeekly, dtype: float64

In [35]:
# Distribution of unique values
cleaned_df['HoursWeekly'].value_counts()

HoursWeekly
40    10100
Name: count, dtype: int64

Everyone works a standard 40 hours at this company.

In [36]:
# Checking the AnnualSalary column
# Descriptive statistics
cleaned_df['AnnualSalary'].describe()

count     10100.000000
mean     120994.773564
std       77358.965898
min      -33326.400000
25%       63440.000000
50%      101774.400000
75%      153717.200000
max      339950.400000
Name: AnnualSalary, dtype: float64

In [37]:
# Looks like AnnualSalary has some negative values - let's calculate a count of negative values
cleaned_df[cleaned_df['AnnualSalary'] < 0]['AnnualSalary'].value_counts().sum()

53

In [38]:
# Converting negative AnnualSalary values to positive
cleaned_df['AnnualSalary'] = cleaned_df['AnnualSalary'].abs()
# Descriptive statistics
cleaned_df['AnnualSalary'].describe()

count     10100.000000
mean     121154.328099
std       77108.817860
min        1307.200000
25%       63440.000000
50%      101774.400000
75%      153717.200000
max      339950.400000
Name: AnnualSalary, dtype: float64

In [39]:
# Min AnnualSalary and Max AnnualSalary are incorrect based off of HourlyRate and HoursWeekly values
cleaned_df['AnnualSalary'].value_counts().sort_index(ascending = True)

AnnualSalary
1307.2      1
1432.0      2
1473.6      1
1515.2      1
1723.2      1
           ..
339846.4    2
339888.0    1
339908.8    1
339929.6    1
339950.4    1
Name: count, Length: 5538, dtype: int64

In [40]:
# Many values are calculated incorrectly, need to make fix AnnualSalary column
# Multiply HourlyRate, HoursWeekly, and 52 weeks in a year
cleaned_df['AnnualSalary'] = round((cleaned_df['HourlyRate'] * cleaned_df['HoursWeekly'] * 52), 2)
# Descriptive statistics
cleaned_df['AnnualSalary'].describe()

count     10100.000000
mean     109903.470416
std       49693.942213
min       35796.800000
25%       64646.400000
50%      101774.400000
75%      153717.200000
max      203985.600000
Name: AnnualSalary, dtype: float64

In [41]:
# Distribution of unique values
cleaned_df['AnnualSalary'].value_counts().sort_index()

AnnualSalary
35796.8     1
35817.6     1
36067.2     4
36108.8     1
36129.6     1
           ..
203860.8    1
203923.2    2
203944.0    1
203964.8    1
203985.6    1
Name: count, Length: 5244, dtype: int64

AnnualSalary column has been fixed! Every salary now looks reasonable for employees at a company.

In [42]:
# Checking DrivingCommuterDistance column
# Descriptive statistics
cleaned_df['DrivingCommuterDistance'].describe()

count    10100.000000
mean        45.165743
std         51.390866
min       -275.000000
25%         13.000000
50%         42.000000
75%         71.000000
max        950.000000
Name: DrivingCommuterDistance, dtype: float64

In [43]:
# Calculating how many negative values there are in DrivingCommuterDistance
cleaned_df[cleaned_df['DrivingCommuterDistance'] < 0]['DrivingCommuterDistance'].value_counts().sum()

1343

In [44]:
# Changing negative values to positive 
cleaned_df['DrivingCommuterDistance'] = cleaned_df['DrivingCommuterDistance'].abs()

In [45]:
# Identify high outliers (over 100 miles)
outliers = cleaned_df['DrivingCommuterDistance'] > 100
outliers.value_counts().sort_index(ascending = False)

DrivingCommuterDistance
True      258
False    9842
Name: count, dtype: int64

In [46]:
# Replace outliers with the median of non-outlier values
median_distance = cleaned_df.loc[~outliers, 'DrivingCommuterDistance'].median()
cleaned_df.loc[outliers, 'DrivingCommuterDistance'] = median_distance
# Descriptive statistics
cleaned_df['DrivingCommuterDistance'].describe()

count    10100.000000
mean        43.154356
std         29.165575
min          0.000000
25%         15.000000
50%         41.000000
75%         68.000000
max         99.000000
Name: DrivingCommuterDistance, dtype: float64

In [47]:
# Distribution of unique values
cleaned_df['DrivingCommuterDistance'].value_counts().sort_index(ascending = False)

DrivingCommuterDistance
99     66
98     58
97     69
96     57
95     66
     ...
4     156
3     163
2     182
1     177
0      89
Name: count, Length: 98, dtype: int64

Looks good now, the largest distance employees drive is 99 miles and the lowest is 0.

In [48]:
# Checking Gender column
# Summary of data
cleaned_df['Gender'].describe()

count      10100
unique         3
top       Female
freq        5756
Name: Gender, dtype: object

In [49]:
# Distribution of unique values
cleaned_df['Gender'].value_counts()

Gender
Female                  5756
Male                    4208
Prefer Not to Answer     136
Name: count, dtype: int64

Looks good!

In [50]:
# Checking MaritalStatus column
# Summary of data
cleaned_df['MaritalStatus'].describe()

count       10100
unique          3
top       Married
freq         3405
Name: MaritalStatus, dtype: object

In [51]:
# Distribution of unique values
cleaned_df['MaritalStatus'].value_counts()

MaritalStatus
Married     3405
Single      3387
Divorced    3308
Name: count, dtype: int64

Looks good!

In [52]:
# Checking the NumCompaniesPreviouslyWorked column
# Descriptive statistics
cleaned_df['NumCompaniesPreviouslyWorked'].describe()

count    10100.000000
mean         4.265248
std          2.407871
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          9.000000
Name: NumCompaniesPreviouslyWorked, dtype: float64

In [53]:
# Distribution of unique values
cleaned_df['NumCompaniesPreviouslyWorked'].value_counts()

NumCompaniesPreviouslyWorked
5.0    1586
1.0    1497
2.0    1469
3.0    1447
4.0    1077
6.0    1047
7.0     679
8.0     652
9.0     646
Name: count, dtype: int64

In [54]:
# Convert to int64 data type since NumCompaniesPreviouslyWorked only has whole numbers
cleaned_df['NumCompaniesPreviouslyWorked'] = cleaned_df['NumCompaniesPreviouslyWorked'].astype(int)
# Checking conversion
cleaned_df['NumCompaniesPreviouslyWorked'].dtype

dtype('int64')

Looks good!

In [55]:
# Checking the AnnualProfessionalDevHrs column
# Descriptive statistics
cleaned_df['AnnualProfessionalDevHrs'].describe()

count    10100.000000
mean        14.926584
std          5.468290
min          5.000000
25%         11.000000
50%         15.000000
75%         19.000000
max         25.000000
Name: AnnualProfessionalDevHrs, dtype: float64

In [56]:
# Convert to int64 data type since AnnualProfessionalDevHrs only has whole numbers
cleaned_df['AnnualProfessionalDevHrs'] = cleaned_df['AnnualProfessionalDevHrs'].astype(int)
# Checking conversion
cleaned_df['AnnualProfessionalDevHrs'].dtype

dtype('int64')

Looks good!

In [57]:
# Checking the PaycheckMethod column
# Summary of the data
cleaned_df['PaycheckMethod'].describe()

count          10100
unique             7
top       Mail Check
freq            4917
Name: PaycheckMethod, dtype: object

In [58]:
# Distribution of unique values
cleaned_df['PaycheckMethod'].value_counts()

PaycheckMethod
Mail Check        4917
Mailed Check      2425
DirectDeposit      988
Direct_Deposit     948
Mail_Check         547
Direct Deposit     226
MailedCheck         49
Name: count, dtype: int64

In [59]:
# Need to standardize the categorical values
# Create a mapping dictionary
paycheck_mapping = {
    'Mail Check': 'MailedCheck', 
    'Mailed Check': 'MailedCheck',
    'Mail_Check': 'MailedCheck',
    'Direct_Deposit': 'DirectDeposit',
    'Direct Deposit': 'DirectDeposit'}

# replace() method
cleaned_df['PaycheckMethod'] = cleaned_df['PaycheckMethod'].replace(paycheck_mapping)
# Distribution of unique values to check if it worked
cleaned_df['PaycheckMethod'].value_counts()

PaycheckMethod
MailedCheck      7938
DirectDeposit    2162
Name: count, dtype: int64

Looks good now!

In [60]:
# Checking the TextMessageOptIn column
# Summary of the data
cleaned_df['TextMessageOptIn'].describe()

count     10100
unique        2
top         Yes
freq       9557
Name: TextMessageOptIn, dtype: object

Looks good!

In [61]:
# Final look-over of the cleaned DataFrame
cleaned_df

,EmployeeNumber,Age,Tenure,Turnover,HourlyRate,HoursWeekly,CompensationType,AnnualSalary,DrivingCommuterDistance,JobRoleArea,Gender,MaritalStatus,NumCompaniesPreviouslyWorked,AnnualProfessionalDevHrs,PaycheckMethod,TextMessageOptIn
0,1,28,6,Yes,24.37,40,Salary,50689.6,89,Research,Female,Married,3,7,MailedCheck,Yes
1,2,33,2,Yes,24.37,40,Salary,50689.6,89,Research,Female,Married,6,7,MailedCheck,Yes
2,3,22,1,No,22.52,40,Salary,46841.6,35,InformationTechnology,Female,Single,1,8,MailedCheck,Yes
3,4,23,1,No,22.52,40,Salary,46841.6,35,InformationTechnology,Female,Single,3,14,MailedCheck,Yes
4,5,40,6,No,88.77,40,Salary,184641.6,12,Sales,Prefer Not to Answer,Single,7,15,MailedCheck,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10095,10096,50,15,Yes,61.78,40,Salary,128502.4,6,Laboratory,Male,Divorced,1,8,MailedCheck,Yes
10096,10097,33,9,Yes,23.28,40,Salary,48422.4,10,Marketing,Male,Single,1,20,DirectDeposit,Yes
10097,10098,31,9,Yes,28.25,40,Salary,58760.0,68,Laboratory,Male,Married,2,21,DirectDeposit,Yes
10098,10099,50,12,No,32.22,40,Salary,67017.6,13,Research,Female,Married,5,20,DirectDeposit,Yes
10099,10100,59,14,No,44.59,40,Salary,92747.2,94,Research,Male,Married,5,10,DirectDeposit,Yes

In [62]:
# Checking the dtypes one last time
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10100 entries, 0 to 10099
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmployeeNumber                10100 non-null  int64
 1   Age                           10100 non-null  int64
 2   Tenure                        10100 non-null  int64
 3   Turnover                      10100 non-null  object
 4   HourlyRate                    10100 non-null  float64
 5   HoursWeekly                   10100 non-null  int64
 6   CompensationType              10100 non-null  object
 7   AnnualSalary                  10100 non-null  float64
 8   DrivingCommuterDistance       10100 non-null  int64
 9   JobRoleArea                   10100 non-null  object
 10  Gender                        10100 non-null  object
 11  MaritalStatus                 10100 non-null  object
 12  NumCompaniesPreviouslyWorked  10100 non-null  int64
 13  AnnualProfessionalDevHrs      10100 non-null  int64
 14  PaycheckMethod                10100 non-null  object
 15  TextMessageOptIn              10100 non-null  object
dtypes: float64(2), int64(7), object(7)
memory usage: 1.3+ MB

In [63]:
# Save the cleaned dataframe to a CSV file
cleaned_df.to_csv('Cleaned Employee Turnover Dataset.csv', index = False)