In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
df = pd.read_csv('Megastore_Dataset_Task_3 3.csv')
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,OrderPriority,Region,Segment,ExpeditedShipping,PaymentMethod,CustomerOrderSatisfaction
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,High,Southeast,Corporate,Yes,PayPal,Dissatisfied
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,High,Southeast,Corporate,Yes,PayPal,Dissatisfied
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied

## Encoding ##

Two ordinal variables: OrderPriority, CustomerOrderSatisfaction

Two nominal variables: Segment, PaymentMethod

In [3]:
df['OrderPriority'].value_counts()

OrderPriority
High      4320
Medium    3914
Name: count, dtype: int64

In [4]:
# Ordinal encoding of OrderPriority
priority = [['Medium', 'High']]
priority_encoder = OrdinalEncoder(categories = priority)
df['OrderPriority_encoded'] = priority_encoder.fit_transform(df[['OrderPriority']])

# Dropping OrderPriority column
df = df.drop('OrderPriority', axis = 1)
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,Region,Segment,ExpeditedShipping,PaymentMethod,CustomerOrderSatisfaction,OrderPriority_encoded
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,Northeast,Corporate,Yes,Credit Card,Satisfied,1.0
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,Northeast,Corporate,Yes,Credit Card,Satisfied,1.0
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,Northeast,Corporate,Yes,Credit Card,Satisfied,1.0
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,Northeast,Corporate,Yes,Credit Card,Satisfied,1.0
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,Northeast,Corporate,Yes,Credit Card,Satisfied,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,Southeast,Corporate,Yes,PayPal,Dissatisfied,1.0
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,Southeast,Corporate,Yes,PayPal,Dissatisfied,1.0
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,Southeast,Consumer,No,Credit Card,Very Satisfied,1.0
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,Southeast,Consumer,No,Credit Card,Very Satisfied,1.0
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,Southeast,Consumer,No,Credit Card,Very Satisfied,1.0

In [5]:
df['OrderPriority_encoded'].value_counts()

OrderPriority_encoded
1.0    4320
0.0    3914
Name: count, dtype: int64

In [6]:
df['CustomerOrderSatisfaction'].value_counts()

CustomerOrderSatisfaction
Prefer not to answer    1880
Very Dissatisfied       1845
Dissatisfied            1589
Very Satisfied          1563
Satisfied               1357
Name: count, dtype: int64

In [7]:
# Ordinal encoding of CustomerOrderSatisfaction
satisfaction = [['Prefer not to answer', 'Dissatisfied', 'Very Dissatisfied', 'Satisfied', 'Very Satisfied']]
satisfaction_encoder = OrdinalEncoder(categories = satisfaction)
df['CustomerOrderSatisfaction_encoded'] = satisfaction_encoder.fit_transform(df[['CustomerOrderSatisfaction']])

# Dropping CustomerOrderSatisfaction column
df = df.drop('CustomerOrderSatisfaction', axis = 1)
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,Region,Segment,ExpeditedShipping,PaymentMethod,OrderPriority_encoded,CustomerOrderSatisfaction_encoded
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,Northeast,Corporate,Yes,Credit Card,1.0,3.0
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,Northeast,Corporate,Yes,Credit Card,1.0,3.0
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,Northeast,Corporate,Yes,Credit Card,1.0,3.0
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,Northeast,Corporate,Yes,Credit Card,1.0,3.0
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,Northeast,Corporate,Yes,Credit Card,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,Southeast,Corporate,Yes,PayPal,1.0,1.0
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,Southeast,Corporate,Yes,PayPal,1.0,1.0
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,Southeast,Consumer,No,Credit Card,1.0,4.0
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,Southeast,Consumer,No,Credit Card,1.0,4.0
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,Southeast,Consumer,No,Credit Card,1.0,4.0

In [8]:
# One hot encoding Segment
df = pd.get_dummies(df, columns = ['Segment'])
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,Region,ExpeditedShipping,PaymentMethod,OrderPriority_encoded,CustomerOrderSatisfaction_encoded,Segment_Consumer,Segment_Corporate
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,Northeast,Yes,Credit Card,1.0,3.0,False,True
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,Northeast,Yes,Credit Card,1.0,3.0,False,True
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,Northeast,Yes,Credit Card,1.0,3.0,False,True
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,Northeast,Yes,Credit Card,1.0,3.0,False,True
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,Northeast,Yes,Credit Card,1.0,3.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,Southeast,Yes,PayPal,1.0,1.0,False,True
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,Southeast,Yes,PayPal,1.0,1.0,False,True
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,Southeast,No,Credit Card,1.0,4.0,True,False
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,Southeast,No,Credit Card,1.0,4.0,True,False
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,Southeast,No,Credit Card,1.0,4.0,True,False

In [9]:
# One hot encoding PaymentMethod
df = pd.get_dummies(df, columns = ['PaymentMethod'])
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,Region,ExpeditedShipping,OrderPriority_encoded,CustomerOrderSatisfaction_encoded,Segment_Consumer,Segment_Corporate,PaymentMethod_Credit Card,PaymentMethod_PayPal
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,Northeast,Yes,1.0,3.0,False,True,True,False
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,Northeast,Yes,1.0,3.0,False,True,True,False
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,Northeast,Yes,1.0,3.0,False,True,True,False
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,Northeast,Yes,1.0,3.0,False,True,True,False
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,Northeast,Yes,1.0,3.0,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,Southeast,Yes,1.0,1.0,False,True,False,True
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,Southeast,Yes,1.0,1.0,False,True,False,True
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,Southeast,No,1.0,4.0,True,False,True,False
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,Southeast,No,1.0,4.0,True,False,True,False
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,Southeast,No,1.0,4.0,True,False,True,False

In [10]:
# One hot encoding ProductName for the market basket analysis
df = pd.get_dummies(df, columns = ['ProductName'], prefix = 'Product')
df

,OrderID,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,Region,ExpeditedShipping,OrderPriority_encoded,...,Product_WRAP VINTAGE PETALS DESIGN,Product_YELLOW COAT RACK PARIS FASHION,Product_YELLOW GIANT GARDEN THERMOMETER,Product_YELLOW SHARK HELICOPTER,Product_ZINC STAR TLIGHT HOLDER,Product_ZINC FOLKART SLEIGH BELLS,Product_ZINC HERB GARDEN CONTAINER,Product_ZINC METAL HEART DECORATION,Product_ZINC TLIGHT HOLDER STAR LARGE,Product_ZINC TLIGHT HOLDER STARS SMALL
0,536370,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,Northeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
1,536370,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,Northeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
2,536370,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,Northeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
3,536370,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,Northeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
4,536370,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,Northeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,12,12/2/11 12:43,$0.85,$10.20,United States,No,Southeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
8230,580263,16,12/2/11 12:43,$0.42,$6.72,United States,No,Southeast,Yes,1.0,...,False,False,False,False,False,False,False,False,False,False
8231,581316,1,12/8/11 11:46,$2.55,$2.55,United States,No,Southeast,No,1.0,...,False,False,False,False,False,False,False,False,False,False
8232,581316,1,12/8/11 11:46,$12.50,$12.50,United States,No,Southeast,No,1.0,...,False,False,False,False,False,False,False,False,False,False
8233,581316,1,12/8/11 11:46,$4.15,$4.15,United States,No,Southeast,No,1.0,...,False,False,False,False,False,False,False,False,False,False

In [11]:
# CSV of cleaned dataset before transactionalizing
df.to_csv('Cleaned_Dataset_Before_Transactionalizing.csv', index = False)

In [12]:
# Selecting only product columns
columns_to_keep = ['OrderID'] + [col for col in df.columns if col.startswith('Product_')]
basket_df = df[columns_to_keep]
basket_df

,OrderID,Product_ 50S CHRISTMAS GIFT BAG LARGE,Product_ DOLLY GIRL BEAKER,Product_ I LOVE LONDON MINI BACKPACK,Product_ NINE DRAWER OFFICE TIDY,Product_ SET 2 TEA TOWELS I LOVE LONDON,Product_ SPACEBOY BABY GIFT SET,Product_ TRELLIS COAT RACK,Product_10 COLOUR SPACEBOY PEN,Product_12 COLOURED PARTY BALLOONS,...,Product_WRAP VINTAGE PETALS DESIGN,Product_YELLOW COAT RACK PARIS FASHION,Product_YELLOW GIANT GARDEN THERMOMETER,Product_YELLOW SHARK HELICOPTER,Product_ZINC STAR TLIGHT HOLDER,Product_ZINC FOLKART SLEIGH BELLS,Product_ZINC HERB GARDEN CONTAINER,Product_ZINC METAL HEART DECORATION,Product_ZINC TLIGHT HOLDER STAR LARGE,Product_ZINC TLIGHT HOLDER STARS SMALL
0,536370,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,536370,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,536370,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,536370,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,536370,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8230,580263,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8231,581316,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8232,581316,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8233,581316,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# Group by OrderID, then drop the index
basket_df = basket_df.groupby('OrderID').any()
basket_df.reset_index(drop = True, inplace = True)  # This removes the OrderID index completely
basket_df

,Product_ 50S CHRISTMAS GIFT BAG LARGE,Product_ DOLLY GIRL BEAKER,Product_ I LOVE LONDON MINI BACKPACK,Product_ NINE DRAWER OFFICE TIDY,Product_ SET 2 TEA TOWELS I LOVE LONDON,Product_ SPACEBOY BABY GIFT SET,Product_ TRELLIS COAT RACK,Product_10 COLOUR SPACEBOY PEN,Product_12 COLOURED PARTY BALLOONS,Product_12 EGG HOUSE PAINTED WOOD,...,Product_WRAP VINTAGE PETALS DESIGN,Product_YELLOW COAT RACK PARIS FASHION,Product_YELLOW GIANT GARDEN THERMOMETER,Product_YELLOW SHARK HELICOPTER,Product_ZINC STAR TLIGHT HOLDER,Product_ZINC FOLKART SLEIGH BELLS,Product_ZINC HERB GARDEN CONTAINER,Product_ZINC METAL HEART DECORATION,Product_ZINC TLIGHT HOLDER STAR LARGE,Product_ZINC TLIGHT HOLDER STARS SMALL
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
437,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
# Save to CSV
basket_df.to_csv('Cleaned_Dataset_Transactionalized.csv', index = False)

## Market Basket Analysis ##

In [15]:
# Apriori algorithm
frequent_itemsets = apriori(basket_df, min_support = 0.01, use_colnames = True)

In [16]:
# Creating the association rules (only want association rules where lift >= 1)
rules = association_rules(frequent_itemsets, metric = 'lift', min_threshold = 1)
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Product_CHARLOTTE BAG DOLLY GIRL DESIGN),(Product_ DOLLY GIRL BEAKER),0.058957,0.020408,0.011338,0.192308,9.423077,0.010135,1.212828,0.949880
1,(Product_ DOLLY GIRL BEAKER),(Product_CHARLOTTE BAG DOLLY GIRL DESIGN),0.020408,0.058957,0.011338,0.555556,9.423077,0.010135,2.117347,0.912500
2,(Product_DOLLY GIRL CHILDRENS BOWL),(Product_ DOLLY GIRL BEAKER),0.040816,0.020408,0.015873,0.388889,19.055556,0.015040,1.602968,0.987842
3,(Product_ DOLLY GIRL BEAKER),(Product_DOLLY GIRL CHILDRENS BOWL),0.020408,0.040816,0.015873,0.777778,19.055556,0.015040,4.316327,0.967262
4,(Product_DOLLY GIRL CHILDRENS CUP),(Product_ DOLLY GIRL BEAKER),0.036281,0.020408,0.013605,0.375000,18.375000,0.012865,1.567347,0.981176
5,(Product_ DOLLY GIRL BEAKER),(Product_DOLLY GIRL CHILDRENS CUP),0.020408,0.036281,0.013605,0.666667,18.375000,0.012865,2.891156,0.965278
6,(Product_ DOLLY GIRL BEAKER),(Product_PLASTERS IN TIN SPACEBOY),0.020408,0.124717,0.013605,0.666667,5.345455,0.011060,2.625850,0.829861
7,(Product_PLASTERS IN TIN SPACEBOY),(Product_ DOLLY GIRL BEAKER),0.124717,0.020408,0.013605,0.109091,5.345455,0.011060,1.099542,0.928756
8,(Product_ DOLLY GIRL BEAKER),(Product_PLASTERS IN TIN WOODLAND ANIMALS),0.020408,0.151927,0.011338,0.555556,3.656716,0.008237,1.908163,0.741667
9,(Product_PLASTERS IN TIN WOODLAND ANIMALS),(Product_ DOLLY GIRL BEAKER),0.151927,0.020408,0.011338,0.074627,3.656716,0.008237,1.058591,0.856684

In [42]:
# Sorting by highest lift values
rules.sort_values(by = 'lift', ascending = False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
75099,"(Product_CARD DOLLY GIRL , Product_ALARM CLOCK...","(Product_CHILDRENS CUTLERY DOLLY GIRL , Produc...",0.011338,0.011338,0.011338,1.0,88.2,0.011209,inf,1.0
73649,"(Product_SET6 RED SPOTTY PAPER PLATES, Product...","(Product_ALARM CLOCK BAKELIKE RED , Product_PL...",0.011338,0.011338,0.011338,1.0,88.2,0.011209,inf,1.0
82960,"(Product_CHILDRENS CUTLERY DOLLY GIRL , Produc...","(Product_ALARM CLOCK BAKELIKE PINK, Product_CA...",0.011338,0.011338,0.011338,1.0,88.2,0.011209,inf,1.0
73668,"(Product_ALARM CLOCK BAKELIKE RED , Product_PL...","(Product_SET6 RED SPOTTY PAPER PLATES, Product...",0.011338,0.011338,0.011338,1.0,88.2,0.011209,inf,1.0
81563,"(Product_ALARM CLOCK BAKELIKE PINK, Product_AL...","(Product_PLASTERS IN TIN CIRCUS PARADE , Produ...",0.011338,0.011338,0.011338,1.0,88.2,0.011209,inf,1.0

In [43]:
# Rule 1
rule_one = rules.sort_values(by = 'lift', ascending = False).iloc[0]
print("Antecedents:", rule_one['antecedents'])
print("Consequents:", rule_one['consequents'])
print("Support:", rule_one['support'])
print("Confidence:", rule_one['confidence'])
print("Lift:", rule_one['lift'])

Antecedents: frozenset({'Product_CARD DOLLY GIRL ', 'Product_ALARM CLOCK BAKELIKE PINK'})
Consequents: frozenset({'Product_CHILDRENS CUTLERY DOLLY GIRL ', 'Product_SPACEBOY BIRTHDAY CARD', 'Product_ALARM CLOCK BAKELIKE RED ', 'Product_CHILDRENS CUTLERY SPACEBOY '})
Support: 0.011337868480725623
Confidence: 1.0
Lift: 88.2

In [44]:
# Rule 2
rule_two = rules.sort_values(by = 'lift', ascending = False).iloc[1]
print("Antecedents:", rule_two['antecedents'])
print("Consequents:", rule_two['consequents'])
print("Support:", rule_two['support'])
print("Confidence:", rule_two['confidence'])
print("Lift:", rule_two['lift'])

Antecedents: frozenset({'Product_SET6 RED SPOTTY PAPER PLATES', 'Product_ROUND SNACK BOXES SET OF4 WOODLAND ', 'Product_ALARM CLOCK BAKELIKE GREEN'})
Consequents: frozenset({'Product_ALARM CLOCK BAKELIKE RED ', 'Product_PLASTERS IN TIN CIRCUS PARADE ', 'Product_SET6 RED SPOTTY PAPER CUPS'})
Support: 0.011337868480725623
Confidence: 1.0
Lift: 88.2

In [45]:
# Rule 3
rule_three = rules.sort_values(by = 'lift', ascending = False).iloc[2]
print("Antecedents:", rule_three['antecedents'])
print("Consequents:", rule_three['consequents'])
print("Support:", rule_three['support'])
print("Confidence:", rule_three['confidence'])
print("Lift:", rule_three['lift'])

Antecedents: frozenset({'Product_CHILDRENS CUTLERY DOLLY GIRL ', 'Product_SPACEBOY BIRTHDAY CARD', 'Product_ALARM CLOCK BAKELIKE RED ', 'Product_ROUND SNACK BOXES SET OF4 WOODLAND '})
Consequents: frozenset({'Product_ALARM CLOCK BAKELIKE PINK', 'Product_CARD DOLLY GIRL ', 'Product_CHILDRENS CUTLERY SPACEBOY '})
Support: 0.011337868480725623
Confidence: 1.0
Lift: 88.2